version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27300:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    image: customersupportsystem
    container_name: customersupport-app
    ports:
      - "8081:8080"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/test_db
      - JWT_SECRET_KEY="1234567890123456789012345678901234567890"
    restart: on-failure

volumes:
  mongo-data:
